// Auto-generated by Kinetic SQL ⚠️ Do NOT import this file manually. It automatically patches the library.

import 'kinetic-sql';

declare module 'kinetic-sql' {
    export interface Register {
        schema: {
            tables: {
            access_codes: {
                id: number;
                code: string;
                role: string;
                can_send_message: boolean| null;
                expires_at: string;
                created_at: string| null;
                can_create_admin: boolean| null;
                token: string| null;
                can_login: boolean| null;
                can_view_requests: boolean| null;
                universal_code: boolean| null;
                auto_login_enabled: boolean| null;
            };
            access_requests: {
                id: number;
                email: string;
                company: string| null;
                status: string| null;
                created_at: string| null;
            };
            calendar_events: {
                id: string;
                user_id: string;
                title: string;
                start_time: string;
                end_time: string| null;
                is_all_day: boolean| null;
                created_at: string| null;
            };
            daily_journal: {
                id: string;
                user_id: string;
                entry_date: string;
                created_at: string| null;
                mood_score: number| null;
                mood_dominant: string| null;
                mood_notes: string| null;
                habits_data: any| null;
                productivity_data: any| null;
                journal_data: any| null;
                template_responses: any| null;
            };
            library_books: {
                id: string;
                user_id: string;
                title: string;
                author: string| null;
                notes: string[]| null;
                created_at: string| null;
            };
            messages: {
                id: number;
                content: string;
                contact_info: string| null;
                used_code: string| null;
                created_at: string| null;
            };
            user_settings: {
                user_id: string;
                active_habits: string[]| null;
                active_productivity_tags: string[]| null;
                template_definitions: any| null;
                updated_at: string| null;
                routine_definitions: any| null;
                affirmations: string[]| null;
                movies: string[]| null;
                quotes: any| null;
                library_lock_code: string| null;
            };
            users: {
                id: string;
                email: string;
                password_hash: string;
                role: string| null;
                created_at: string| null;
            };
            };
            functions: {
                migrate_dynamic_todos: {
                    args: Record<string, any>;
                    returns: any;
                };
                update_journal_summary: {
                    args: Record<string, any>;
                    returns: any;
                };
                append_task_to_today: {
                    args: Record<string, any>;
                    returns: any;
                };
            };
        };
    }
}
